/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Cahrt31: typeof import('./src/components/charts/cahrt3-1.vue')['default']
    Car: typeof import('./src/components/tres/Car.vue')['default']
    Chart11: typeof import('./src/components/charts/chart1-1.vue')['default']
    Chart12: typeof import('./src/components/charts/chart1-2.vue')['default']
    Chart13: typeof import('./src/components/charts/chart1-3.vue')['default']
    Chart21: typeof import('./src/components/charts/chart2-1.vue')['default']
    Chart22: typeof import('./src/components/charts/chart2-2.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    EndCard: typeof import('./src/components/EndCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sense: typeof import('./src/components/Sense.vue')['default']
    Station: typeof import('./src/components/tres/Station.vue')['default']
    Task2Card: typeof import('./src/components/Task2Card.vue')['default']
    Task3Card: typeof import('./src/components/Task3Card.vue')['default']
    TestCar: typeof import('./src/components/TestCar.vue')['default']
    Track: typeof import('./src/components/tres/Track.vue')['default']
  }
}
declare module '@tauri-apps/api/tauri' 
